# Generated by Django 5.2.17 on 2026-08-24 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(max_length=150, verbose_name='Nome de quem pede')),
                ('beneficiary_name', models.CharField(max_length=150, verbose_name='Para quem devemos orar?')),
                ('prayer_text', models.TextField(verbose_name='Pedido de oração')),
                ('status', models.CharField(choices=[('new', 'Novo'), ('praying', 'Em oração'), ('closed', 'Encerrado')], db_index=True, default='new', max_length=20, verbose_name='Status')),
                ('is_reserved', models.BooleanField(db_index=True, default=False, verbose_name='Pedido reservado')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data do registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de encerramento')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prayer_requests', to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado por')),
            ],
            options={
                'verbose_name': 'Pedido de oração',
                'verbose_name_plural': 'Pedidos de oração',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PrayerAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Criado'), ('updated', 'Alterado')], max_length=20)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prayer_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='prayers.prayerrequest')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
